<div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">404 - Page Not Found</h2>
                    <p class="lead">The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from.</p>
                    <p><b>Or you could just press this neat little button:</b></p>
                    <a href="<?php echo $this->url('home'); ?>" class="btn btn-large btn-success"><i class="icon-home icon-white"></i> Take Me Home</a>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/front/img/error404.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->
