	<nav class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
        	<?php foreach ($this->itens as $key => $item): ?>
                <?php $url = (null == $item['siteContent']) ? $item['url'] : $this->contentUrl($item['siteContent']); ?>

                <?php if (empty($item['childrens'])): ?>
                <li>
                    <a href="<?php echo $url; ?>"><?php echo $item['title']; ?></a>
                </li>

                <?php else: ?>
                <li class="dropdown">
                    <a href="#"  class="dropdown-toggle js-activated"><?php echo $item['title']; ?></a>
                    <ul class="dropdown-menu">
                    <?php foreach ($item['childrens'] as $key => $cItem): ?>
                        <?php $url = (null == $cItem['siteContent']) ? $cItem['url'] : $this->contentUrl($cItem['siteContent']); ?>
                        <?php if (empty($cItem['childrens'])): ?>
                        <li>
                            <a href="<?php echo $url; ?>"><?php echo $cItem['title']; ?></a>
                        </li>

                        <?php else: ?>
		                <li class="dropdown-submenu">
		                    <a href="#"><?php echo $cItem['title']; ?></a>
		                    <ul class="dropdown-menu">
		                    <?php foreach ($cItem['childrens'] as $key => $subItem): ?>
		                        <?php $url = (null == $subItem['siteContent']) ? $subItem['url'] : $this->contentUrl($subItem['siteContent']); ?>
		                        <li>
		                            <a href="<?php echo $url; ?>"><?php echo $subItem['title']; ?></a>
		                        </li>

		                    <?php endforeach ?>
		                    </ul>
		                </li>
		                <?php endif ?>
                    <?php endforeach ?>
                    </ul>
                </li>
                <?php endif ?>

            <?php endforeach ?>
        </ul>
    </nav>
