    <li><a target="_blank" href="https://www.facebook.com/leandro.lugaresi"><i class="icon-s-facebook"></i></a></li>
    <li><a target="_blank" href="https://github.com/leandro-lugaresi"><i class="icon-s-github"></i></a></li>
    <li><a target="_blank" href="http://open.spotify.com/user/leandrolugaresi"><i class="icon-s-spotify"></i></a></li>
    <li><a target="_blank" href="http://instagram.com/leandrolugaresi"><i class="icon-s-instagram"></i></a></li>
	<li><a target="_blank" href="https://twitter.com/leandrolugaresi"><i class="icon-s-twitter"></i></a></li>
