    <li><a target="_blank" href="https://twitter.com/leandrolugaresi"><i class="icon-s-twitter"></i></a></li>
    <li><a target="_blank" href="https://www.facebook.com/leandro.lugaresi"><i class="icon-s-facebook"></i></a></li>
    <li><a target="_blank" href="br.linkedin.com/in/leandrolugaresi/"><i class="icon-s-linkedin"></i></a></li>
    <li><a target="_blank" href="http://instagram.com/leandrolugaresi"><i class="icon-s-instagram"></i></a></li>
