<div id="portfolio" class="section anchor">
		<div class="dark-wrapper">
			<div class="container inner">
				<h2 class="section-title text-center">Projetos desenvolvidos</h2>
				<p class="lead main text-center">Sistemas desenvolvidos com dedicação, sempre buscando a superação das espectativas.</p>
				<div class="grid-portfolio fix-portfolio">
					<ul class="filter">
						<li><a class="active" href="#" data-filter="*">All</a></li>
						<?php foreach ($this->categorys as $category): ?>
							<li><a href="#" data-filter=".<?php echo str_replace(' ', '-', $category->getName()); ?>"><?php echo $category->getName(); ?></a></li>
						<?php endforeach ?>
					</ul>
          			<!-- /filter -->

          			<ul class="items">
          				<?php foreach ($this->portfolios as $item): ?>
          					<?php
          						$config = $this->getConfigsTemplate(get_class($item),$item->getId());
          						$categorysClass = '';
          						foreach ($item->getContentCategorys() as $category) {
          							$categorysClass .= ' '.str_replace(' ', '-', $category->getName());
          						}
          					?>
          					<li class="item thumb <?php echo $categorysClass; ?>">
			              		<figure>
				              		<a target="_blank" href="<?php echo $this->contentUrl($item); ?>" data-contenturl="<?php echo $this->contentUrl($item); ?>">
				                	<div class="text-overlay">
					                  	<div class="info"><?php echo $item->getTitle(); ?></div>
					                </div>
					                <img src="<?php echo $this->imageThumb($config->imageHeader,'384','288'); ?>" alt="" /> </a>
				                </figure>
				            </li>
          				<?php endforeach; ?>
          			</ul>
          			<!-- /.items -->
        		</div>
        		<!-- /.portfolio -->
      		</div>
    	</div>
  	</div>
  	<!-- /#portfolio -->
