	<div id="contact" class="section anchor">
		<div class="dark-wrapper">
			<div class="container inner">
				<div class="thin text-center">
					<h2 class="section-title text-center">Entre em contato!</h2>
					<p class="lead main text-center"></p>
					<p>Estou sempre online. Se precisar falar comigo, escolha alguma das opções abaixo e inicie a conversa, você não vai se arrepender! ;)</p>
					<ul class="contact-info">
						<li><i class="icon-mail"></i><a href="mailto:leandrolugaresi92@gmail.com">leandrolugaresi92@gmail.com</a> </li>
						<li><i class="icon-phone"></i>+55 (54) 9975 5458</li>
						<li><i class="icon-s-skype"></i>leandrolugaresi</li>
					</ul>
					<div class="divide50"></div>
					<div class="form-container">
						<div class="response alert alert-success"></div>
						<?php
							$form = $this->form;

							$form->setAttribute('class', 'forms');
							$form->prepare();
							echo $this->formtwb($form);
						?>
					</div>
					<!-- /.form-container -->
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div id="map"></div>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1xdEVYy8IZdBKJGQp_QpDWaNQT7ZHGhY&sensor=false&extension=.js"></script>
		<script>
			google.maps.event.addDomListener(window, 'load', init);
			var map;
			function init() {
				var mapOptions = {
					center: new google.maps.LatLng(-29.283010, -51.493136),
					zoom: 15,
					zoomControl: true,
					zoomControlOptions: {
						style: google.maps.ZoomControlStyle.DEFAULT,
					},
					disableDoubleClickZoom: false,
					mapTypeControl: true,
					mapTypeControlOptions: {
						style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
					},
					scaleControl: true,
					scrollwheel: false,
					streetViewControl: true,
					draggable : true,
					overviewMapControl: false,
					mapTypeId: google.maps.MapTypeId.ROADMAP,
					styles: [{stylers:[{saturation:-100},{gamma:1}]},{elementType:"labels.text.stroke",stylers:[{visibility:"off"}]},{featureType:"poi.business",elementType:"labels.text",stylers:[{visibility:"off"}]},{featureType:"poi.business",elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"poi.place_of_worship",elementType:"labels.text",stylers:[{visibility:"off"}]},{featureType:"poi.place_of_worship",elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"road",elementType:"geometry",stylers:[{visibility:"simplified"}]},{featureType:"water",stylers:[{visibility:"on"},{saturation:50},{gamma:0},{hue:"#50a5d1"}]},{featureType:"administrative.neighborhood",elementType:"labels.text.fill",stylers:[{color:"#333333"}]},{featureType:"road.local",elementType:"labels.text",stylers:[{weight:0.5},{color:"#333333"}]},{featureType:"transit.station",elementType:"labels.icon",stylers:[{gamma:1},{saturation:50}]}]
				}

				var mapElement = document.getElementById('map');
				var map = new google.maps.Map(mapElement, mapOptions);
				var locations = [
					['R. Padre Arlindo Maçon, 106, RS, 95185-000', -29.283010, -51.493136]
				];
				for (i = 0; i < locations.length; i++) {
					marker = new google.maps.Marker({
						icon: '/front/images/map-pin.png',
						position: new google.maps.LatLng(locations[i][1], locations[i][2]),
						map: map
					});
				}
			}
		</script>
	</div>
	<!-- /#contact -->
