<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php
        $children = $this->viewModel()->getCurrent()->getChildren();
        $variables = $children[0]->getVariables();
        if (isset($variables['entity']) && isset($variables['id'])) {
            $metatags = $this->getMetatags(get_class($variables['entity']),$variables['id']);
        }else{
            $metatags = $this->getMetatags('','');
        }
        $this->headTitle()->setSeparator(' - ')->setAutoEscape(false);

        foreach ($metatags['title'] as $title) {
            $this->headTitle($title);
        }
        echo $this->headTitle();
    ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('author',$metatags['author'])
        ->appendName('description',$metatags['description'])
        ->appendName('robots',$metatags['robots'])
        ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/front/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/front/css/bootstrap.css')
                    ->appendStylesheet($this->basePath() . '/front/css/settings.css')
                    ->appendStylesheet($this->basePath() . '/front/css/owl.carousel.css')
                    ->appendStylesheet($this->basePath() . '/front/js/google-code-prettify/prettify.css')
                    ->appendStylesheet($this->basePath() . '/front/js/fancybox/jquery.fancybox.css')
                    ->appendStylesheet($this->basePath() . '/front/js/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.2')
                    ->appendStylesheet($this->basePath() . '/front/css/style.css')
                    ->appendStylesheet($this->basePath() . '/front/css/color/red.css')
                    ->appendStylesheet($this->basePath() . '/front/type/fontello.css')
                    ->appendStylesheet($this->basePath() . '/front/type/budicons.css')
                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Josefin+Sans:400,600,700,400italic,600italic,700italic')
                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900')
                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800')
                    ->appendStylesheet($this->basePath() . '/assets/modulus/plugins/x-editable/css/bootstrap-editable.css');
    ?>

            <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53f506330575af58"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="style/js/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class='icon-menu-1'></i>
                        </a>
                        <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">
                            <img src="/front/images/logo-icon.png" alt="" data-src="/front/images/logo-icon.png" data-ret="/front/images/logo-icon-retina.png" class="retina" />
                        </a>
                    </div>
                    <?php echo $this->renderMenu('header', 'front/layout/partials/navbar'); ?>
                </div>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        <div class="col-sm-6 col-sm-offset-3"><?php $this->Notification(); ?></div>

        <?php echo $this->content; ?>


        <footer class="footer black-wrapper widget-footer">
            <div class="container inner">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Sobre mim</h3>
                            <p>Meu nome é Leandro Lugaresi, sou gaúcho de Carlos Barbosa e sou graduado em Análise e Desenvolvimento de Sistemas.</p>
                            <p>Programo em PHP com banco de dados MySQL. Faço sites gerenciáveis, sistemas e manutenções diversas, seja um projeto novo ou já existente.</p>
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /col -->
                    <?php echo $this->recentPosts('front/blog/partials/footer-recent-posts'); ?>

                    <div class="col-sm-5">
                        <div class="widget">
                            <h3 class="widget-title">Instagram</h3>
                            <div class="instagram-widget">
                                <ul id="instawidget">
                                </ul>
                            </div>
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">© 2014 Leandro Lugaresi. All rights reserved. Create with <a href="/produtos/visualizar/1/moduluscmf">ModulusCMF</a>.</p>
                    <ul class="social pull-right">
                        <?php echo $this->partial('front/layout/partials/social-block'); ?>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!-- .body-wrapper -->
    <?php
    echo $this->inlineScript()->prependFile('/front/js/scripts.js')
                        ->prependFile('/front/js/google-code-prettify/prettify.js')
                        ->prependFile('/front/js/retina.js')
                        ->prependFile('/front/js/instafeed.min.js')
                        ->prependFile('/front/js/jquery.slickforms.js')
                        ->prependFile('/front/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.0')
                        ->prependFile('/front/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.2')
                        ->prependFile('/front/js/jquery.fancybox.pack.js')
                        ->prependFile('/front/js/jquery.fitvids.js')
                        ->prependFile('/front/js/jquery.isotope.min.js')
                        ->prependFile('/front/js/owl.carousel.min.js')
                        ->prependFile('/front/js/jquery.easytabs.min.js')
                        ->prependFile('/front/js/jquery.themepunch.plugins.min.js')
                        ->prependFile('/front/js/jquery.themepunch.revolution.min.js')
                        ->prependFile('/front/js/twitter-bootstrap-hover-dropdown.min.js')
                        ->prependFile('/front/js/bootstrap.min.js')
                        ->prependFile('/front/js/jquery.min.js');
    ?>
</body>
</html>
