<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <?php
        $children = $this->viewModel()->getCurrent()->getChildren();
        $variables = $children[0]->getVariables();
        if (isset($variables['entity']) && isset($variables['id'])) {
            $metatags = $this->getMetatags(get_class($variables['entity']),$variables['id']);
        }else{
            $metatags = $this->getMetatags('','');
        }
        $this->headTitle()->setSeparator(' - ')->setAutoEscape(false);

        foreach ($metatags['title'] as $title) {
            $this->headTitle($title);
        }
        echo $this->headTitle();
    ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ->appendName('author',$metatags['author'])
        ->appendName('description',$metatags['description'])
        ->appendName('robots',$metatags['robots'])
        ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/front/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/front/css/foundation.min.css')
                    ->appendStylesheet($this->basePath() . '/front/css/styles.css')
                    ->appendStylesheet($this->basePath() . '/front/titan/css/jquery.titanlighbox.css')
                    ->appendStylesheet($this->basePath() . '/front/rs-plugin/css/settings.css')
                    ->appendStylesheet($this->basePath() . '/front/css/colors.css')
                    ->appendStylesheet('http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600')
                    ->appendStylesheet($this->basePath() . '/assets/modulus/plugins/x-editable/css/bootstrap-editable.css');
    ?>

    <!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

    <!-- HEADER -->
    <div id="header">
        <div class="row">
            <div class="three columns">
                <a href="<?php echo $this->url('home'); ?>" title="Leandro Lugaresi" id="logo"></a>
            </div>
            <!-- Fixed navbar -->
            <?php echo $this->renderMenu('header', 'front/layout/partials/navbar'); ?>
            <div class="shadow-down"></div>
        </div>
    </div>
    <!--END HEADER -->

    <?php $this->Notification(); ?>
    <?php echo $this->content; ?>

    <!-- FOOTER -->
    <div class="container footer">
        <div class="row">
            <div class="three columns">
                <h5>Navigation</h5>
                <div class="list-type-footer">
                    <ul>
                        <li> <a href="index-2.html">Home</a> </li>
                        <li> <a href="team.html">Pages</a> </li>
                        <li> <a href="typography.html">Shortcodes</a> </li>
                        <li> <a href="blog.html">Blog</a> </li>
                        <li> <a href="portfolio_4_col.html">Portfolio</a> </li>
                        <li> <a href="contact.html">Contact</a> </li>
                    </ul>
                </div>
            </div>
            <div class="three columns">
                <h5>Monthly Archives</h5>
                <div class="list-type-footer">
                    <ul>
                        <li> <a href="index-2.html">February 2013</a> </li>
                        <li> <a href="portfolio_4_col.html">January 2013</a> </li>
                        <li> <a href="blog.html">December 2012</a> </li>
                        <li> <a href="features.html">November 2012</a> </li>
                        <li> <a href="contact.html">October 2012</a> </li>
                    </ul>
                </div>
            </div>
            <div class="three columns">
                <h5>Latest Posts</h5>
                <p><a href="single_post.html"> <img class="img_float_left" src="/front/images/thumb_1.jpg" width="40" height="40" alt=
                "" /> <strong>Nullam dictum felis eu</strong></a><br />
                Lorem ipsum dolor sit amet.</p>
                <p><a href="single_post.html"> <img class="img_float_left" src="/front/images/thumb_2.jpg" width="40" height="40" alt=
                "" /> <strong>Nullam dictum felis eut</strong></a><br />
                Lorem ipsum dolor sit amet.</p>
                <p><a href="single_post.html"> <img class="img_float_left" src="/front/images/thumb_3.jpg" width="40" height="40" alt=
                "" /> <strong>Nullam dictum felis eu</strong></a><br />
                Lorem ipsum dolor sit amet.</p>
            </div>
            <div class="three columns">
                <h5>Contact Us</h5>
                <img class="img_float_left" src="/front/images/footer_icon_1.png" alt="" />
                <p> (+44) 773 339 9999 </p>
                <img class="img_float_left" src="/front/images/footer_icon_2.png" alt="" />
                <p> <a href="mailto:youremailaddress">info@yourwebsite.com</a> </p>
                <img src="/front/images/footer_icon_3.png" alt="" class="img_float_left" />
                <p class="tab"> <strong>Your Company LDT</strong><br />
                Street nr 100<br />
                London, NW1 2RG<br />
                UK </p>
            </div>
        </div>
    </div>
    <!-- END FOOTER -->
    <!-- SUBFOOTER -->
    <div class="container subfooter">
        <div class="row">
            <div class="six columns">
                <p> &#169; Copyright - Leandro Lugaresi</p>
            </div>
            <div class="six columns">
                <div class="large-social-block">
                    <a href="#"><span class="social github"></span></a>
                    <a href="#"><span class="social linkedin"></span></a>
                    <a href="#"><span class="social google"></span></a>
                    <a href="#"><span class="social twitter"></span></a>
                    <a href="#"><span class="social facebook"></span></a>
                </div>
            </div>
        </div>
    </div>
    <!-- END SUBFOOTER -->
    <?php
    //adiciono os principais scripts com espaco para serem adicionados outros
    echo $this->inlineScript()->prependFile('/front/titan/js/prettify.js')
                        ->prependFile('/front/titan/js/jquery.titanlighbox.js')
                        ->prependFile('/front/js/scripts.js')
                        ->prependFile('/front/js/jquery.infieldlabel.min.js')
                        ->prependFile('/front/js/jquery.themepunch.revolution.min.js')
                        ->prependFile('/front/rs-plugin/js/jquery.themepunch.plugins.min.js')
                        ->prependFile('/front/js/app.js')
                        ->prependFile('/front/js/modernizr.foundation.js')
                        ->prependFile('/front/js/foundation.min.js')
                        ->prependFile('/front/js/jquery.min.js');

    ?>
</body>
</html>
