<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'BjyAuthorize',
        'ZendDeveloperTools',
        'SlmMail',
        'Soflomo\Purifier',
        'ModulusBase',
        'ModulusForm',
        'ModulusUser',
        'ModulusAcl',
        'InterfaceContent',
        'ModulusFileManager',
        'ModulusDataTables',
        'ModulusCrud',
        'ModulusUI',
        'ModulusMail',
        'ModulusConfig',
        'ModulusLog',
        'ModulusContent',
        'ModulusProducts',
        'SlmGoogleAnalytics',
        'ModulusCEO',
        'ModulusCache',
        'ModulusContact',
        'Front',
    ),
    'service_manager' => array('factories' => array('Navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory')),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
        )
    );
