<?php $this->inlineScript()->captureStart(); ?>
		if (!filemanager){
            var filemanager = {};
        }
<?php $this->inlineScript()->captureEnd(); ?>

<?php
	$form = $this->form;
    $form->setAttribute('class',' row-border');
	$form->prepare();
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-body">
                <?php echo $this->formTwb($form); ?>
			</div>
		</div>
	</div>
</div>
