  	<div id="home" class="section">
		<div class="light-wrapper">
			<?php echo $this->partial('front/index/slide.phtml'); ?>
    	</div>
  	</div>
	<div id="services" class="section anchor">
		<div class="light-wrapper">
			<div class="container inner">
				<h2 class="section-title text-center">Serviços</h2>
				<p class="lead main text-center">O que eu posso fazer para você</p>
				<div class="row text-center services-1">

					<div class="col-sm-4">
						<div class="col-wrapper">
							<div class="icon-wrapper"> <i class="budicon-browser-3"></i> </div>
							<h3>Desenvolvimento de web-sites</h3>
							<p>Criação de websites completos, desde o design, passando pelo html/css/javascript até o desenvolvimento do gerenciador de conteúdo.</p>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="col-wrapper">
							<div class="icon-wrapper"> <i class="budicon-code"></i> </div>
							<h3>Web Developer</h3>
							<p>Agências me mandam um belo template (HTML, CSS e Javascript), e eu o transformo em um belo site/portal/FacebookApp com o conteúdo gerenciável e qualquer funcionalidade necessária ao projeto.</p>
						</div>
					</div>
					<div class="col-sm-4">
						<div class="col-wrapper">
							<div class="icon-wrapper"> <i class="budicon-cube"></i> </div>
							<h3>Desenvolvimento personalizado</h3>
							<p>Desenvolvo ferramentas e customizações para sistemas Open Source.</p>
						</div>
					</div>
				</div>
				<!-- /.services -->

			</div>
		<!-- /.container -->
		</div>
	</div>
	<!-- /#home -->
  	<div class="parallax parallax3 customers">
		<div class="container inner text-center">
			<div class="testimonials owl-carousel thin">
				<div class="item">
					<blockquote>
						<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nullam dolor nibh ultricies vehicula ut id elit vulputate Tristique Egestas.<small>Nikolas Brooten</small></p>
					</blockquote>
				</div>
				<div class="item">
					<blockquote>
						<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas faucibus mollis interdum. Etiam porta sem malesuada magna mollis euismod.<small>Coriss Ambady</small></p>
					</blockquote>
				</div>
				<div class="item">
					<blockquote>
						<p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis id vestibulum. Donec sed odio dui. Sed posuere consectetur est at lobortis.<small>Barclay Widerski</small></p>
					</blockquote>
				</div>
				<div class="item">
					<blockquote>
						<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas faucibus mollis interdum. Vivamus sagittis lacus vel augue laoreet.<small>Elsie Spear</small></p>
					</blockquote>
				</div>
			</div>
		</div>
		<!-- /.container -->
  	</div>
  	<!-- /.parallax -->
	<div id="portfolio" class="section anchor">
		<div class="dark-wrapper">
			<div class="container inner">
				<h2 class="section-title text-center">Projetos desenvolvidos</h2>
				<p class="lead main text-center">Sistemas desenvolvidos com dedicação, sempre buscando entregar a superação das espectativas.</p>
				<div class="grid-portfolio fix-portfolio">
					<ul class="filter">
						<li><a class="active" href="#" data-filter="*">All</a></li>
						<?php foreach ($this->categorys as $category): ?>
							<li><a href="#" data-filter=".<?php echo str_replace(' ', '-', $category->getName()); ?>"><?php echo $category->getName(); ?></a></li>
						<?php endforeach ?>
					</ul>
          			<!-- /filter -->

          			<ul class="content-slider items">
          				<?php foreach ($this->portfolios as $item): ?>
          					<?php
          						$config = $this->getConfigsTemplate(get_class($item),$item->getId());
          						$categorysClass = '';
          						foreach ($item->getContentCategorys() as $category) {
          							$categorysClass .= ' '.str_replace(' ', '-', $category->getName());
          						}
          					?>
          					<li class="item thumb <?php echo $categorysClass; ?>">
			              		<figure>
				              		<a href="<?php echo $this->contentUrl($item); ?>" data-contenturl="<?php echo $this->contentUrl($item); ?>" data-callback="callPortfolioScripts();" data-contentcontainer=".pcw">
				                	<div class="text-overlay">
					                  	<div class="info"><?php echo $item->getTitle(); ?></div>
					                </div>
					                <img src="<?php echo $this->imageThumb($config->imageHeader,'384','288'); ?>" alt="" /> </a>
				                </figure>
				            </li>
          				<?php endforeach; ?>
          			</ul>
          			<!-- /.items -->
        		</div>
        		<!-- /.portfolio -->
      		</div>
    	</div>
  	</div>
  	<!-- /#portfolio -->

	<div class="parallax parallax2 work-together">
		<div class="container inner text-center">
			<h1> Agilize o desenvolvimento <span class="colored">&</span> qualidade dos seus sites</h1>
			<div class="divide10"></div>
			<div class="smooth"><a href="#contact" class="btn btn-border-lite">Vamos trabalhar juntos</a></div>
		</div>
		<!-- /.container -->
	</div>
	<!-- /.parallax -->

  	<div id="about" class="section anchor">
    	<div class="light-wrapper">
      		<div class="container inner">
        		<h2 class="section-title text-center">Sobre mim</h2>
        		<p class="lead main text-center">Conheça o programador que você está contratando</p>
        		<div class="row">
					<div class="col-sm-8">
						<p>Meu nome é Leandro Lugaresi, sou gaúcho de Carlos Barbosa, tenho 22 anos e sou graduado em Análise e Desenvolvimento de Sistemas.
							Trabalhei na agencia <a href="http://www.icub.com.br/">CUB</a>, onde eu aprendi muito e participei de vários projetos e após isso comecei a trabalhar como freelancer.</p>
						<p>Sou desenvolvedor PHP com um conhecimento avançado, trabalho com PHP e sempre que possível utilizo o <a href="http://framework.zend.com/">Zend Framework 2</a> com <a href="http://www.doctrine-project.org/">Doctrine 2</a> para o desenvolvimento de sistemas web.</p>
					</div>
					<div class="col-sm-4">
						<figure><img src="/front/images/art/about.jpg" alt="" /></figure>
					</div>
				</div>
        		<div class="divide60"></div>
        		<div class="row">
          			<div class="col-sm-4">
            			<div class="section-title">
              				<h3>Minhas habilidades</h3>
            			</div>
            			<!-- <p>.</p> -->
            			<div class="divide10"></div>
            			<ul class="progress-list">
              				<li>
                				<p>PHP <em>90%</em></p>
                				<div class="progress plain">
                  					<div class="bar" style="width: 90%;"></div>
                				</div>
              				</li>
							<li>
								<p>ZF2 <em>75%</em></p>
								<div class="progress plain">
								<div class="bar" style="width: 75%;"></div>
								</div>
							</li>
							<li>
								<p>MySQL <em>85%</em></p>
								<div class="progress plain">
								<div class="bar" style="width: 85%;"></div>
								</div>
							</li>
							<li>
								<p>Doctrine2 <em>80%</em></p>
								<div class="progress plain">
								<div class="bar" style="width: 80%;"></div>
								</div>
							</li>
						</ul>
            			<!-- /.progress-list -->
          			</div>
      				<div class="col-sm-4">
			            <div class="section-title">
							<h3>Por que me escolher?</h3>
			            </div>
            			<div class="divide5"></div>
            			<div class="panel-group" id="accordion">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"> <a data-toggle="collapse" class="panel-toggle active" data-parent="#accordion" href="#collapseOne">Segurança</a> </h4>
								</div>
								<div id="collapseOne" class="panel-collapse collapse in">
									<div class="panel-body">Aplicações com foco na segurança, utilização de validações CSRF, Validação dos dados de formulários e utilização do ORM Doctrine 2 evitando SQL injection.</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"> <a data-toggle="collapse" class="panel-toggle" data-parent="#accordion" href="#collapseTwo">Performance</a> </h4>
								</div>
								<div id="collapseTwo" class="panel-collapse collapse">
									<div class="panel-body">O Zend Framework 2 foi projetado visando desempenho, tornando-o muito veloz e versátil.</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"> <a data-toggle="collapse" class="panel-toggle" data-parent="#accordion" href="#collapseThree">Modular</a> </h4>
								</div>
								<div id="collapseThree" class="panel-collapse collapse">
									<div class="panel-body">O Zend Framework 2 é modular e com isso o código do sistema fica separado em módulos tornando-o muito mais simples e de fácil manutenção.</div>
								</div>
							</div>
            			</div>
          			</div>
					<div class="col-sm-4">
						<div class="section-title">
							<h3>Meus produtos</h3>
						</div>
						<div class="services-2">
							<div class="row">
								<div class="col-sm-12">
									<div class="bm20">
										<div class="icon"> <i class="budicon-cube icn"></i> </div>
										<!-- /.icon -->
										<div class="text">
											<h4>ModulusCMF</h4>
											<p>Framework para a criação de Sistemas de gerenciamento de conteúdo. Com o Modulus eu crio o CMS perfeito para as suas necessidades. </p>
										</div>
										<!-- /.text -->
									</div>
								<!-- /.div -->
								</div>
							<!-- /.col-sm-12 -->
							</div>
							<!-- /.row -->
						</div>
						<!-- /.col-services -->
					</div>
        		</div>
       			<hr />
        		<h2 class="text-center">Minha equipe</h2>
				<div class="row team text-center">
					<div class="col-sm-offset-2 col-sm-4">
						<figure><img src="/front/images/leandro.jpg" alt="" /></figure>
						<h3>Leandro Lugaresi</h3>
						<span class="biz-title colored">Web Developer</span>
						<ul class="social">
							<li><a href="https://twitter.com/leandrolugaresi"><i class="icon-s-twitter"></i></a></li>
							<li><a href="https://www.facebook.com/leandro.lugaresi"><i class="icon-s-facebook"></i></a></li>
							<li><a href="http://instagram.com/leandrolugaresi"><i class="icon-s-instagram"></i></a></li>
							<li><a href="https://www.linkedin.com/in/leandrolugaresi"><i class="icon-s-linkedin"></i></a></li>
						</ul>
					</div>
					<div class="col-sm-4">
						<figure><img src="/front/images/yuki2.jpg" alt="" /></figure>
						<h3>Yuki</h3>
						<span class="biz-title colored">O cão</span>
						<p>Meu cão que me acompanha na jornada de trabalho e me ajuda a ter uma vida mais saudável.</p>
					</div>
				</div>
      		</div>
    	</div>
  	</div>
  	<!-- /#about -->
