<div class="fullscreenbanner-container revolution">
				<div class="fullscreenbanner">
					<ul>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-delay="13000" >
							<!-- MAIN IMAGE -->
							<img src="/front/images/slides/06.jpg"  alt="slide01"  data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption finewide_large_white customin customout tp-resizeme"
								data-x="center" data-hoffset="0"
								data-y="center" data-voffset="-40"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="500"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="chars"
								data-elementdelay="0.08"
								data-endelementdelay="0.08"
								data-end="4000"
					data-endspeed="500"
								style="z-index: 2; max-width: auto; max-height: auto; white-space: nowrap;">Leandro Lugaresi
							</div>

							<!-- LAYER NR. 2 -->
							<div class="tp-caption whitedivider3px customin customout tp-resizeme"
								data-x="center" data-hoffset="0"
								data-y="center" data-voffset="0"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="800"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-end="4000"
					data-endspeed="500"
								style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;">&nbsp;
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption finewide_medium_white randomrotate customout tp-resizeme"
								data-x="center" data-hoffset="0"
								data-y="center" data-voffset="30"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="500"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="chars"
								data-elementdelay="0.08"
								data-endelementdelay="0.08"
								data-end="4000"
					data-endspeed="500"
								style="z-index: 4; max-width: auto; max-height: auto; white-space: nowrap;">Desenvolvedor PHP
							</div>

							<!-- LAYER NR. 4 -->
							<div class="tp-caption boldwide_small_white customin customout tp-resizeme"
								data-x="190"
								data-y="120"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="300"
								data-start="5000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.08"
								data-endelementdelay="0.08"
								data-endspeed="300"
								style="z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;">
								<strong>Desenvolvimento</strong>
							</div>



							<!-- LAYER NR. 5 -->
							<div class="tp-caption whitedivider3px_vertical customin tp-resizeme"
								data-x="530"
								data-y="110"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="300"
								data-start="5500"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.1"
								data-endelementdelay="0.1"
								data-endspeed="300"
								style="z-index: 6; max-width: auto; max-height: auto; white-space: nowrap;">&nbsp;
							</div>

							<!-- LAYER NR. 6 -->
							<div class="tp-caption finewide_small_white randomrotate customout tp-resizeme"
								data-x="550"
								data-y="120"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="6400"
								data-easing="Power3.easeInOut"
								data-splitin="chars"
								data-splitout="chars"
								data-elementdelay="0.08"
								data-endelementdelay="0.08"
								data-endspeed="300"
								style="z-index: 7; max-width: auto; max-height: auto; white-space: nowrap;">WEBSITES
							</div>

							<!-- LAYER NR. 7 -->
							<div class="tp-caption finewide_small_white customin customout tp-resizeme"
								data-x="550"
								data-y="160"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="7200"
								data-easing="Power3.easeInOut"
								data-splitin="words"
								data-splitout="words"
								data-elementdelay="0.12"
								data-endelementdelay="0.12"
								data-endspeed="300"
								style="z-index: 8; max-width: auto; max-height: auto; white-space: nowrap;">PORTAIS
							</div>

							<!-- LAYER NR. 8 -->
							<div class="tp-caption finewide_small_white customin customout tp-resizeme"
								data-x="550"
								data-y="200"
								data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="500"
								data-start="8000"
								data-easing="Power3.easeInOut"
								data-splitin="none"
								data-splitout="none"
								data-elementdelay="0.08"
								data-endelementdelay="0.08"
								data-endspeed="300"
								style="z-index: 9; max-width: auto; max-height: auto; white-space: nowrap;">FACEBOOK APP`S
							</div>

							<!-- LAYER NR. 9 -->
							<div class="tp-caption finewide_verysmall_white_mw customin customout tp-resizeme"
								data-x="550"
								data-y="250"
								data-customin="x:0;y:50;z:0;rotationX:-120;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 0%;"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0;scaleY:0;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="900"
								data-start="8000"
								data-easing="Power3.easeInOut"
								data-splitin="lines"
								data-splitout="lines"
								data-elementdelay="0.2"
								data-endelementdelay="0.08"
								data-endspeed="300"
								style="z-index: 10; max-width: auto; max-height: auto; white-space: nowrap;">
								Desenvolvimento utilizando as melhores tecnologias do mercado,<br/>sistemas com segurança, performance e confiabilidade em mente.<br/>
							</div>


						</li>
						<li data-transition="fade">
							<img src="/front/images/slides/01.jpg" alt="" />
							<div class="caption large lite sfb" data-x="center" data-y="245" data-speed="900" data-start="800" data-easing="Sine.easeOut">Procurando Frelancer PHP?</div>
							<div class="caption small lite sfb" data-x="center" data-y="319" data-speed="900" data-start="1500" data-easing="Sine.easeOut">Sou um desenvolvedor PHP, especialista em ZendFramework2!</div>
							<div class="caption small lite sfb" data-x="center" data-y="362" data-speed="900" data-start="2200" data-easing="Sine.easeOut">
								<div class="smooth"><a href="#portfolio" class="btn btn-border-lite">Veja meus projetos</a></div>
							</div>
						</li>
						<li data-transition="fade" data-slotamount="7" data-masterspeed="300" >
							<!-- MAIN IMAGE -->
							<img src="/front/images/slides/workspace.jpg"  alt="slider3"  data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption sfl"
								data-x="450"
								data-y="115"
								data-speed="900"
								data-start="100"
								data-easing="Sine.easeOut"
								data-endspeed="300"
								style="z-index: 2"><img src="/front/images/slides/modulus-macbook.png" alt="">
							</div>

							<!-- LAYER NR. 2 -->
							<div class="tp-caption sfl"
								data-x="800"
								data-y="180"
								data-speed="900"
								data-start="900"
								data-easing="Sine.easeOut"
								data-endspeed="300"
								style="z-index: 3"><img src="/front/images/slides/modulus-ipad.png" alt="">
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption sfl"
								data-x="980"
								data-y="290"
								data-speed="900"
								data-start="1600"
								data-easing="Sine.easeOut"
								data-endspeed="300"
								style="z-index: 4"><img src="/front/images/slides/modulus-iphone.png" alt="">
							</div>

							<!-- LAYER NR. 4 -->
							<div class="tp-caption large sfl tp-resizeme"
								data-x="35"
								data-y="180"
								data-speed="900"
								data-start="1500"
								data-easing="Expo.easeOut"
								data-endspeed="300"
								style="z-index: 5">CMS moderno
							</div>

							<!-- LAYER NR. 5 -->
							<div class="tp-caption small sfr tp-resizeme"
								data-x="35"
								data-y="240"
								data-speed="900"
								data-start="1800"
								data-easing="Expo.easeOut"
								data-endspeed="300"
								style="z-index: 6"><span style="color:#fcd68a">responsivo</span>
							</div>
							<div class="tp-caption small sfr tp-resizeme"
								data-x="35"
								data-y="260"
								data-speed="900"
								data-start="1800"
								data-easing="Expo.easeOut"
								data-endspeed="300"
								style="z-index: 6"><span style="color:#fcd68a">Open Source</span>
							</div>
							<div class="tp-caption small sfr tp-resizeme"
								data-x="35"
								data-y="280"
								data-speed="900"
								data-start="1800"
								data-easing="Expo.easeOut"
								data-endspeed="300"
								style="z-index: 6"><span style="color:#fcd68a">Seguro</span>
							</div>
							<div class="tp-caption small sfr tp-resizeme"
								data-x="35"
								data-y="300"
								data-speed="900"
								data-start="1800"
								data-easing="Expo.easeOut"
								data-endspeed="300"
								style="z-index: 6"><span style="color:#fcd68a">ZF2</span>
							</div>

							<!-- LAYER NR. 6 -->
							<div class="caption small sfb" data-x="35" data-y="340" data-speed="900" data-start="2200" data-easing="Expo.easeOut">
								<div class="smooth"><a href="/produtos/visualizar/1/moduluscmf" class="btn btn-border-lite">Conheça o produto</a></div>
							</div>
						</li>
          			</ul>
          			<div class="tp-bannertimer tp-bottom"></div>
        		</div>
        		<div class="arrow scroll">
        			<a href="">
        				<i class="icon-down-open-big"></i>
        			</a>
        		</div>
        		<!-- /.fullscreenbanner -->
      		</div>
      		<!-- /.fullscreenbanner-container -->
