<div class="light-wrapper">
    <div class="container inner">
        <div class="row">
            <?php $config = $this->getConfigsTemplate(get_class($this->entity),$this->entity->getId()); ?>
            <?php if (!empty($config->imageHeader)): ?>
            <figure class="main">
                <img src="<?php echo $config->imageHeader; ?>" alt="">
            </figure>
            <?php endif ?>
            <h2 class="section-title text-center"><?php echo $this->entity->getTitle(); ?></h2>
            <?php echo $this->entity->getText(); ?>
        </div>
        <!-- /.row -->
        <?php $galleryItens = $this->getGallery(get_class($entity),$entity->getId()); ?>
        <?php if (!empty($galleryItens)): ?>
            <div class="divide20"></div>
            <div class="inner tp0">
                <div class="carousel-gallery-wrapper">
                    <div class="carousel-gallery custom-controls">
                    <?php foreach ($galleryItens as $key => $item): ?>
                        <?php $item = $item->getFile(); ?>
                        <div class="item">
                        <?php if (in_array($item->getFiletype()->getName(), array('youtube', 'vimeo'))): ?>
                            <iframe src="<?php echo $this->videoThumb()->getEmbed($item->getPath()); ?>" width="700" height="500"></iframe>
                        <?php else: ?>
                            <img src="<?php echo $this->imageThumb($item->getPath(),700,500); ?>" alt="<?php echo $item->getTitle(); ?>">
                        <?php endif ?>
                        </div>
                    <?php endforeach ?>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
    <!-- /.container -->
</div>
<!-- /.light-wrapper -->
