<?php $config = $this->getConfigsTemplate(get_class($this->entity),$this->entity->getId()); ?>
    <div class="offset"></div>
    <div class="pcw">
        <?php echo $this->partial('front/content/partials/'.$config->galleryType, array('config' => $config, 'entity' => $this->entity)); ?>
        <div class="dark-wrapper">
            <div class="container inner text-center">
                <h1 class="share-button">Click <span class="colored">&</span> Share the Love</h1>
                <div class="share-links">
                    <ul>
                        <li><a class="btn share-facebook" href="#">Like</a></li>
                        <li><a class="btn share-twitter" href="#">Tweet</a></li>
                        <li><a class="btn share-pinterest" href="#">Pin it</a></li>
                    </ul>
                </div>
                <!-- /.share-links -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.dark-wrapper -->
    </div>
    <!-- /.pcw -->
