<?php $config = $this->getConfigsTemplate(get_class($this->entity),$this->entity->getId()); ?>
<?php if (!empty($config->imageHeader)): ?>
    <div class="intro-header" style="background: url(<?php echo $config->imageHeader; ?>) no-repeat center center;">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1 <?php echo (!empty($config->colorHeader)) ? 'style="color: '.$config->colorHeader.'"' : '' ; ?>><?php echo $this->entity->getTitle(); ?></h1>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->
    </div>
<?php endif ?>
    <!-- /.intro-header -->
    <div id="features">
        <div class="container">
            <div class="row">
                <?php if (empty($config->imageHeader)): ?>
                <h1 class="centered"><?php echo $this->entity->getTitle(); ?></h1>
                <?php endif; ?>
                <br>
                <br>
                <div class="col-md-offset-2 col-md-8">
                    <?php echo $this->entity->getText(); ?>
                </div>
            </div>
        </div><!--/ .container -->
    </div><!--/ #features -->

    <?php $galleryItens = $this->getGallery(get_class($entity),$entity->getId()); ?>

    <?php if (!empty($galleryItens)): ?>
    <div id="showcase">
        <div class="container">
            <div class="row">
                <h1 class="centered">Galeria</h1>
                <br>
                <div class="col-lg-8 col-lg-offset-2">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                        <?php $first = true; ?>
                        <?php foreach ($galleryItens as $key => $item): ?>
                            <li data-target="#carousel-example-generic" data-slide-to="<?php echo $key; ?>" class="<?php echo ($first) ? 'active' : ''; ?>"></li>
                            <?php $first = false; ?>
                        <?php endforeach ?>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                        <?php $first = true; ?>
                        <?php foreach ($galleryItens as $key => $item): ?>
                            <?php $item = $item->getFile(); ?>
                            <div class="item <?php echo ($first) ? 'active' : ''; ?>">
                                <?php if (in_array($item->getFiletype()->getName(), array('youtube', 'vimeo'))): ?>
                                    <iframe src="<?php echo $this->videoThumb()->getEmbed($item->getPath()); ?>" width="750" height="421"></iframe>
                                <?php else: ?>
                                    <img src="<?php echo $this->imageThumb($item->getPath(),750,431); ?>" alt="<?php echo $item->getTitle(); ?>">
                                <?php endif ?>
                            </div>
                        <?php $first = false; ?>
                        <?php endforeach ?>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <br>
        </div><!-- /container -->
    </div>
    <?php endif ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">Autor</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-lg-4">
                            <img src="<?php echo $this->imageThumb($entity->getAuthor()->getPerfil()->getPhoto(), '150', '150'); ?>" alt="Perfil" class="img-thumbnail">
                        </div>
                        <div class="col-lg-8">
                            <h3><?php echo $entity->getAuthor()->getFirstName().' '. $entity->getAuthor()->getLastName(); ?></h3>
                            <p><?php echo $entity->getAuthor()->getPerfil()->getAbout(); ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
