<div class="light-wrapper">
    <div class="container inner">
        <div class="row">
            <div class="col-sm-8 content">
                <div class="blog-posts classic-blog">
                    <div class="post">
                        <?php $config = $this->getConfigsTemplate(get_class($this->entity),$this->entity->getId()); ?>
                        <?php if (!empty($config->imageHeader)): ?>
                            <figure class="main"><img src="<?php echo $config->imageHeader; ?>" alt="" /></figure>
                        <?php endif; ?>
                        <div class="post-content">
                            <h1 class="post-title"><?php echo $this->entity->getTitle(); ?></h1>
                            <div class="meta">
                                <span class="date"><?php echo $this->entity->getDatePublished()->format('d-m-Y'); ?></span>
                                <span class="categories">
                                    <?php $first = true; ?>
                                    <?php foreach ($this->entity->getContentCategorys() as $category): ?>
                                        <?php echo (!$first) ? ', ' : ''; ?><a href="<?php echo $this->url('home/blog', array('category' =>  str_replace(' ', '-', $category->getName()) )); ?>"><?php echo $category->getName() ?></a>
                                        <?php $first = false; ?>
                                    <?php endforeach ?>
                                </span>
                                <span class="comments"><a href="#disqus_thread">0 Comment</a></span>
                            </div>
                            <?php echo $this->entity->getText(); ?>
                            <!-- <div class="meta tags"><a href="#">journal</a>, <a href="#">illustration</a>, <a href="#">design</a>, <a href="#">daily</a></div> -->

                            <hr />
                            <div class="text-center">
                                <h1 class="share-button">Click <span class="colored">&</span> Share the Love</h1>
                                <!-- Go to www.addthis.com/dashboard to customize your tools -->
                                <div class="addthis_sharing_toolbox"></div>
                                <!-- <div class="share-links">
                                    <ul>
                                        <li><a class="btn share-facebook" href="#">Like</a></li>
                                        <li><a class="btn share-twitter" href="#">Tweet</a></li>
                                        <li><a class="btn share-pinterest" href="#">Pin it</a></li>
                                    </ul>
                                </div> -->
                                <!-- /.share-links -->
                            </div>

                        </div>
                    </div>
                </div>
                <!-- /.blog-posts -->

                <hr />
                <div class="about-author image-caption">
                    <div class="author-image"> <img alt="" src="<?php echo $this->imageThumb($entity->getAuthor()->getPerfil()->getPhoto(), 120,120); ?>" /> </div>
                    <div class="author-details">
                        <h3>About the author</h3>
                        <p><?php echo $entity->getAuthor()->getPerfil()->getAbout(); ?></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <hr />
                <?php echo $this->disqs($entity->getId().'-'.$entity->getUrl()); ?>
                <!-- /#comments -->
                <hr />

            </div>
            <!-- /.content -->
            <aside class="col-sm-4 sidebar lp30">
                <div class="sidebox widget">
                    <form action="<?php echo $this->url('home/blog'); ?>" class="searchform" method="get">
                        <input type="hidden" id="s1" name="search" value="true" />
                        <input type="text" id="s2" name="query" value="type and hit enter" onfocus="this.value=''" onblur="this.value='type and hit enter'"/>
                    </form>
                </div>
                <!-- /.widget -->
                <?php echo $this->recentPosts('front/blog/partials/sidebar-recent-posts'); ?>
                <!-- /.widget -->
                <div class="sidebox widget">
                    <div class="section-title">
                        <h3 class="widget-title">Também estou aqui</h3>
                    </div>
                    <p>Se quiser entrar em contato comigo ou saber o que estou fazendo, acesse os meus perfis em redes sociais.</p>
                    <ul class="social">
                        <?php echo $this->partial('front/layout/partials/social-block'); ?>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <!-- /.widget -->

                <?php echo $this->sidebarCategorys(); ?>
                <!-- /.widget -->
            </aside>
            <!-- /.col-sm-4 .sidebar -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</div>
<!-- /.light-wrapper -->
